spring:
  application:
    name: Product-Microservice
    #Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/productDB
    username: embarkx
    password: embarkx

  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format-sql: true

#Server configuration
server:
  port: 8081